### PR TITLE
Fix bug #12 - Make logic clearer; remove unnecessary method; Separate out `DescriptorUtils`

### LINKED ISSUE #12: A bug on overriding nested property of a non-configurable property
#### Steps to reproduce:
```js
var base = {};

Object.defineProperty(base, 'a', {
    value: {},
    writable: true,
    enumerable: true,
    configurable: false
});

AG_defineProperty('a.b', { value: 1 }, base);
AG_defineProperty('a.c.d', { value: 2 }, base);

base.a.c = {};

console.log(base.a.c.d);
```

#### Expected:
`2`

#### Actual:
`undefined`

### PR DESCRIPTION
**Pull request by theseanl**
This fixes https://github.com/AdguardTeam/deep-override/issues/12: an issue reported by @AdamWr affecting a filter for `wp.pl` on browser extensions.

While fixing it I improved some other points:
 - Generic property descriptors in access side-effect descriptors are not being applied
 - most of static methods are now moved to `DescriptorUtils`

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -395,7 +415,38 @@ suite('AG_defineProperty', function() {
...
+            let desc = Object.getOwnPropertyDescriptor(base, 'a');
+            assert.equal(desc.configurable, false);
+        });
     });
+
+    suite('Parsing path', function() {
+        test('should parse escaped properties correctly', function() {
+            AG_defineProperty('ಠ_ಠ\b\f.\n\\.\\r\r\t\x2e\v', { value: true }, base);
+
+            base["ಠ_ಠ\b\f"] = {};
```
Comment (ameshkov) [inline test/index.js:445]: Lol :)

**Review by ameshkov — APPROVED** [review]
It took me quite some time to figure how it works, navigation among classes inside a single file is not very convenient in VS code (I started with addProperty, then applyObjectStateRaw located far from it, had to jump here and there).

Filed a new task (do when you can spare time on this):
https://github.com/AdguardTeam/deep-override/issues/14
